#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 JacobJandon — https://github.com/JacobJandon/OnionClaw
"""
OnionClaw — First-Run Setup Wizard
===================================
Creates .env from .env.example (if not present), prompts for LLM credentials,
and writes a minimal Tor torrc that enables the ControlPort needed for
renew_identity() (circuit rotation).

Usage:
  python3 setup.py
"""
import os
import sys
import shutil
import subprocess

_DIR   = os.path.dirname(os.path.abspath(__file__))
_ENV   = os.path.join(_DIR, ".env")
_EXAMPLE = os.path.join(_DIR, ".env.example")
# Also check parent dir for the Sicry repo copy
_ENV_PARENT   = os.path.join(_DIR, "..", ".env")
_EXAMPLE_PARENT = os.path.join(_DIR, "..", ".env.example")

TORRC_SNIPPET = """\
# ── OnionClaw required settings ──────────────────────────────────
ControlPort 9051
CookieAuthentication 1
# DataDirectory /tmp/tor_data   # uncomment to use a custom data dir
# ─────────────────────────────────────────────────────────────────
"""

TORRC_CANDIDATE_PATHS = [
    "/etc/tor/torrc",
    "/usr/local/etc/tor/torrc",
    os.path.expanduser("~/.torrc"),
]

# Custom torrc written to /tmp/tor_data/torrc when system torrc is unwritable
CUSTOM_TORRC_DIR  = "/tmp/tor_data"
CUSTOM_TORRC_PATH = os.path.join(CUSTOM_TORRC_DIR, "torrc")

BOLD  = "\033[1m"
GREEN = "\033[32m"
YELLOW= "\033[33m"
RED   = "\033[31m"
CYAN  = "\033[36m"
RESET = "\033[0m"


def _p(msg, color=""):
    print(f"{color}{msg}{RESET}" if color else msg)


def _ask(prompt, default=""):
    try:
        val = input(f"{CYAN}{prompt}{RESET} [{default}]: ").strip()
        return val if val else default
    except (KeyboardInterrupt, EOFError):
        print()
        sys.exit(0)


def _yes(prompt):
    try:
        ans = input(f"{CYAN}{prompt}{RESET} [Y/n]: ").strip().lower()
        return ans in ("", "y", "yes")
    except (KeyboardInterrupt, EOFError):
        print()
        sys.exit(0)


# ─────────────────────────────────────────────────────────────────
# 1.  .env setup
# ─────────────────────────────────────────────────────────────────

def setup_env():
    _p("\n═══════════════════════════════════════════════════", BOLD)
    _p("  OnionClaw Setup — Step 1: .env configuration", BOLD)
    _p("═══════════════════════════════════════════════════", BOLD)

    if os.path.exists(_ENV):
        _p(f"\n✓ .env already exists: {_ENV}", GREEN)
        if not _yes("  Re-configure anyway?"):
            return

    # Find the best .env.example
    example = _EXAMPLE if os.path.exists(_EXAMPLE) else (
              _EXAMPLE_PARENT if os.path.exists(_EXAMPLE_PARENT) else None)

    if example:
        shutil.copy2(example, _ENV)
        _p(f"\n✓ Copied {os.path.relpath(example, _DIR)} → {os.path.relpath(_ENV, _DIR)}", GREEN)
    else:
        # Write a minimal .env if no example found
        with open(_ENV, "w") as f:
            f.write("# OnionClaw .env — generated by setup.py\n")
            f.write("LLM_PROVIDER=openai\n")
            f.write("TOR_SOCKS_HOST=127.0.0.1\nTOR_SOCKS_PORT=9050\n")
            f.write("TOR_CONTROL_HOST=127.0.0.1\nTOR_CONTROL_PORT=9051\n")
            f.write("SICRY_MAX_CHARS=8000\nSICRY_CACHE_TTL=600\n")
        _p(f"\n✓ Created minimal .env at {_ENV}", GREEN)

    # Interactive prompts ──────────────────────────────────────────
    _p("\nChoose your LLM provider:")
    _p("  1) openai      (OPENAI_API_KEY required)")
    _p("  2) anthropic   (ANTHROPIC_API_KEY required)")
    _p("  3) gemini      (GEMINI_API_KEY required)")
    _p("  4) ollama      (local — no key needed)")
    _p("  5) llamacpp    (local — no key needed)")
    choice = _ask("Enter number", "1")
    provider_map = {"1": "openai", "2": "anthropic", "3": "gemini",
                    "4": "ollama",  "5": "llamacpp"}
    provider = provider_map.get(choice, "openai")

    api_key = ""
    key_var = ""
    if provider == "openai":
        key_var = "OPENAI_API_KEY"
        api_key = _ask("OpenAI API key (sk-...)", "")
    elif provider == "anthropic":
        key_var = "ANTHROPIC_API_KEY"
        api_key = _ask("Anthropic API key (sk-ant-...)", "")
    elif provider == "gemini":
        key_var = "GEMINI_API_KEY"
        api_key = _ask("Gemini API key (AIza...)", "")
    elif provider in ("ollama", "llamacpp"):
        _p(f"  → {provider} uses a local server — no API key needed.", GREEN)

    # Patch the .env file
    _patch_env("LLM_PROVIDER", provider)
    if key_var and api_key:
        _patch_env(key_var, api_key)
    _patch_env("SICRY_CACHE_TTL", "600")  # ensure cache TTL is set

    _p(f"\n✓ .env configured with provider={provider}", GREEN)

    # Copy to parent Sicry repo as well
    parent_env = os.path.join(_DIR, "..", ".env")
    if not os.path.exists(parent_env):
        try:
            shutil.copy2(_ENV, parent_env)
            _p(f"✓ Also copied to parent Sicry repo: {os.path.abspath(parent_env)}", GREEN)
        except Exception:
            pass


def _patch_env(key: str, value: str):
    """Update or append a key=value line in .env."""
    if not os.path.exists(_ENV):
        return
    with open(_ENV, "r") as f:
        lines = f.readlines()
    found = False
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith(f"{key}=") or stripped.startswith(f"# {key}="):
            lines[i] = f"{key}={value}\n"
            found = True
            break
    if not found:
        lines.append(f"{key}={value}\n")
    with open(_ENV, "w") as f:
        f.writelines(lines)


# ─────────────────────────────────────────────────────────────────
# 2.  Tor ControlPort / torrc setup
# ─────────────────────────────────────────────────────────────────

def setup_tor():
    _p("\n═══════════════════════════════════════════════════", BOLD)
    _p("  OnionClaw Setup — Step 2: Tor ControlPort", BOLD)
    _p("═══════════════════════════════════════════════════", BOLD)
    _p("""
renew_identity() needs a Tor ControlPort to rotate circuits.
Without it, Tor keeps the same identity for the entire session.

Required torrc lines:
  ControlPort 9051
  CookieAuthentication 1
""")

    # Check if tor is installed
    tor_bin = shutil.which("tor")
    if not tor_bin:
        _p("⚠  Tor binary not found in PATH.", YELLOW)
        _p("   Install:  sudo apt install tor   (Debian/Ubuntu)", YELLOW)
        _p("             brew install tor        (macOS)", YELLOW)
        _p("             pacman -S tor           (Arch)", YELLOW)
    else:
        _p(f"✓ Tor found: {tor_bin}", GREEN)

    # Try to patch system torrc
    patched_system = False
    for torrc_path in TORRC_CANDIDATE_PATHS:
        if os.path.exists(torrc_path):
            if _already_has_controlport(torrc_path):
                _p(f"\n✓ ControlPort already configured in {torrc_path}", GREEN)
                patched_system = True
                break
            if _yes(f"\nPatch {torrc_path} to add ControlPort settings? (requires write access)"):
                try:
                    with open(torrc_path, "r") as f:
                        existing = f.read()
                    with open(torrc_path, "a") as f:
                        f.write(f"\n{TORRC_SNIPPET}")
                    _p(f"✓ Patched {torrc_path}", GREEN)
                    patched_system = True
                    break
                except PermissionError:
                    _p(f"  Permission denied — try:  sudo python3 setup.py", YELLOW)
                except Exception as e:
                    _p(f"  Failed: {e}", RED)

    if not patched_system:
        # Fall back: write custom torrc + instruct user to start tor with it
        _write_custom_torrc()

    # Print instructions regardless
    _p("""
─────────────────────────────────────────────────────────
  AFTER configuring torrc, restart Tor:

    sudo systemctl restart tor        # systemd (Debian/Ubuntu)
    sudo service tor restart          # SysV init
    brew services restart tor         # macOS Homebrew
    tor -f /tmp/tor_data/torrc &      # custom torrc (no root needed)

─────────────────────────────────────────────────────────
""", CYAN)

    # Verify ControlPort is reachable now
    _verify_controlport()


def _already_has_controlport(path: str) -> bool:
    try:
        with open(path, "r") as f:
            content = f.read()
        return any(
            line.strip().lower().startswith("controlport")
            for line in content.splitlines()
            if not line.strip().startswith("#")
        )
    except Exception:
        return False


def _write_custom_torrc():
    _p(f"\nWriting custom torrc → {CUSTOM_TORRC_PATH}", CYAN)
    try:
        os.makedirs(CUSTOM_TORRC_DIR, exist_ok=True)
        if os.path.exists(CUSTOM_TORRC_PATH) and _already_has_controlport(CUSTOM_TORRC_PATH):
            _p(f"✓ ControlPort already in {CUSTOM_TORRC_PATH}", GREEN)
        else:
            full_torrc = (
                "# OnionClaw custom torrc\n"
                f"DataDirectory {CUSTOM_TORRC_DIR}\n"
                + TORRC_SNIPPET
            )
            with open(CUSTOM_TORRC_PATH, "w") as f:
                f.write(full_torrc)
            _p(f"✓ Written: {CUSTOM_TORRC_PATH}", GREEN)
            _p(f"\n  Also set in .env:")
            _p(f"    TOR_DATA_DIR={CUSTOM_TORRC_DIR}")
        # Set TOR_DATA_DIR in .env so sicry.py finds the cookie
        _patch_env("TOR_DATA_DIR", CUSTOM_TORRC_DIR)
        _p(f"✓ TOR_DATA_DIR={CUSTOM_TORRC_DIR} written to .env", GREEN)
    except Exception as e:
        _p(f"  Could not write custom torrc: {e}", RED)
        _p("  Manual setup required — see README.md#tor-control-port", YELLOW)


def _verify_controlport():
    _p("\nChecking ControlPort connectivity …")
    try:
        import socket
        s = socket.create_connection(("127.0.0.1", 9051), timeout=2)
        s.close()
        _p("✓ ControlPort 9051 is open", GREEN)
    except Exception:
        _p("✗ ControlPort 9051 not reachable yet", YELLOW)
        _p("  → Start/restart Tor with the updated torrc config above.", YELLOW)


# ─────────────────────────────────────────────────────────────────
# 3.  Dependency check
# ─────────────────────────────────────────────────────────────────

def check_deps():
    _p("\n═══════════════════════════════════════════════════", BOLD)
    _p("  OnionClaw Setup — Step 3: Python dependencies", BOLD)
    _p("═══════════════════════════════════════════════════", BOLD)

    required = [
        ("requests",    "requests[socks]"),
        ("bs4",         "beautifulsoup4"),
        ("dotenv",      "python-dotenv"),
        ("stem",        "stem"),
    ]

    missing = []
    for pkg, pip_name in required:
        try:
            __import__(pkg)
            _p(f"  ✓ {pip_name}", GREEN)
        except ImportError:
            _p(f"  ✗ {pip_name}  — MISSING", RED)
            missing.append(pip_name)

    if missing:
        _p(f"\n  Install missing packages:", YELLOW)
        cmd = f"pip install {' '.join(missing)}"
        _p(f"    {cmd}", YELLOW)
        if _yes("  Install them now?"):
            subprocess.run([sys.executable, "-m", "pip", "install", *missing])
    else:
        _p("\n  All dependencies satisfied.", GREEN)


# ─────────────────────────────────────────────────────────────────
# 4.  Final summary
# ─────────────────────────────────────────────────────────────────

def summary():
    _p("\n═══════════════════════════════════════════════════", BOLD)
    _p("  Setup complete!", BOLD + GREEN)
    _p("═══════════════════════════════════════════════════", BOLD)
    _p(f"""
Quick-start commands:

  1. Start Tor (if not running):
       sudo systemctl start tor
       — or —
       tor -f {CUSTOM_TORRC_PATH} &

  2. Verify everything works:
       python3 sicry.py check_tor

  3. Run a full pipeline search:
       python3 pipeline.py --query "your topic"

  4. Run without an LLM key (raw results):
       python3 pipeline.py --query "your topic" --no-llm

  5. MCP server mode (for Claude Desktop / Cursor / Zed):
       python3 sicry.py serve

  Docs: https://github.com/JacobJandon/OnionClaw
""", CYAN)


# ─────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    _p(f"""
{'═' * 51}
  OnionClaw First-Run Setup Wizard
  Press Ctrl+C at any prompt to abort.
{'═' * 51}""", BOLD)

    setup_env()
    setup_tor()
    check_deps()
    summary()
